### ISSUE TITLE
Test case is failing

### ISSUE THREAD

**Issue by ajayinfoworks** [jcustenborder/kafka-connect-spooldir#1]
Followed these steps:

cd ~/source
git clone git@github.com:jcustenborder/connect-utils.git
cd connect-utils
mvn clean install

Got this:

Failed tests:   timestampTests(io.confluent.kafka.connect.utils.data.type.JsonNodeTest): expected:<1451275679192> but was:<1451282879192>

Now trying with:

mvn install -DskipTests

**Comment by jcustenborder** [comment]
Thanks @ajayinfoworks: I'm looking into this in the other repository. It looks to be a time zone issue because it works fine on my laptop which is CST but it failing after I put it on a jenkins box in UTC.

**Comment by jcustenborder** [comment]
Hey @ajayinfoworks Can you pull the repo and give it another shot? I corrected the failing test case and now I'm deploying connect-utils to maven. You no longer need to do that step.

**Comment by ajayinfoworks** [comment]
Thanks @jcustenborder . All the Test cases passed. Seems like I no longer have to build connect-utils separately.
