### ISSUE TITLE
"confluent/schemaConfig-registry" is not a valid repository/tag

### ISSUE THREAD

**Issue by gregroberti** [jcustenborder/kafka-connect-spooldir#10]
$ docker-compose up
Pulling schema-registry (confluent/schemaConfig-registry:latest)...
Error parsing reference: "confluent/schemaConfig-registry" is not a valid repository/tag

**Comment by jcustenborder** [comment]
Thanks @gregroberti! Curse you find and replace. I'll push a change shortly.

**Comment by jcustenborder** [comment]
This is corrected.
