### ISSUE TITLE
Add transformation to copy metadata headers to a field on the key or value.

### ISSUE THREAD

**Issue by jcustenborder** [jcustenborder/kafka-connect-spooldir#107]

**Comment by ChhatralaNirmal** [comment]
Hi @jcustenborder - Is it possible to extract metadata field (file name) from headers field and add a new field in value to store file name with this enhancement ? We have a need to save file name as one of separate value field and send it to downstream system. 
I tried to set metadata.location=FIELD and metadata.field=filename, but that isn't creating or saving the file.name value in separate field. We also tried extractfield smt option but that didn't work either. 
Can you please help us if this is possible with latest version of this connector and how do we achieve it ? few lines of working connect config settings would really help us to adjust our config parameters.  Thanks for your guidance!

**Comment by jcustenborder** [comment]
@ChhatralaNirmal Give this example a look. This will work with the 2.0.58 version and later of spooldir. https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-transform-common/transformations/examples/HeaderToField.spooldir.html
