### ISSUE TITLE
<Question> Does the connector tail the file?

### ISSUE THREAD

**Issue by benitocm** [jcustenborder/kafka-connect-spooldir#111]
Hi,

I am interested in Kafka File Source connector to ingest in real time the logs generated by an application server (i.e. tail the log file and ingest it into Kafka). Please could you tell me if this connector supports that functionality?

Thanks in advance

**Comment by jcustenborder** [comment]
No this connector does not tail the file. It reads the entire file. You could use [file.minimum.age.ms](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-spooldir/sources/SpoolDirCsvSourceConnector.html#file-minimum-age-ms) and roll the file every so often. For example you could roll your file every minute. This setting will look at the last write time of the file and if it's greater than say 1000 ms it'll read it.

**Comment by benitocm** [comment]
Thanks very much for the information
