### ISSUE TITLE
question about batch.size?

### ISSUE THREAD

**Issue by xs005** [jcustenborder/kafka-connect-spooldir#112]
I got error when I try to read 100MB csv file. It shows the message is larger than the max.message.bytes. I try to change batch.size, but it doesn't work. I don't want to change the setting of broker and producer. How a message is defined in kafka-connect-spooldir? Is there a way to reduce the message size by some setting?

**Comment by jcustenborder** [comment]
@xs005 That error message happens when an individual message is bigger than the max message size, it doesn't really have anything to do with the number of messages that are in flight. Is there a possibility that the message is just really large?
