### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by jipiccardi** [jcustenborder/kafka-connect-spooldir#113]
I am having this build error when executing mvn clean package.
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/52015938/64547198-823de300-d302-11e9-8a17-13cda6dcbf5d.PNG">

**Comment by jcustenborder** [comment]
Hi @jipiccardi!

I have no clue if this will actually compile on windows. Which branch are you attempting to compile?

**Comment by jipiccardi** [comment]
Thanks for the fast answer and sorry for my poor english.

I was following a tutorial to read csv files, and i need this connector so i follow the build instruction as specified in README and compile with maven.
I didnt knew that it was made for linux, so i am going to try with this.

Thanks!

**Comment by jcustenborder** [comment]
It's written for java so it could work, it's just not tested on windows. All of the builds I do are on mac or linux. If you want to download it already built try [here](https://www.confluent.io/hub/jcustenborder/kafka-connect-spooldir).

**Comment by jipiccardi** [comment]
i have just installed it on linux, thank you!
