### ISSUE TITLE
include.file.metadata absent in current options

### ISSUE THREAD

**Issue by Hubbitus** [jcustenborder/kafka-connect-spooldir#116]
In https://devhub.io/repos/jcustenborder-kafka-connect-spooldir described option `include.file.metadata`, but it looks like it is not present in current version.

Is it possible to resurrect it?

**Comment by Hubbitus** [comment]
Sorry, are you interesting in the PR for that?

**Comment by jcustenborder** [comment]
@Hubbitus @malamut54 Have you tested out the [2.0](https://github.com/jcustenborder/kafka-connect-spooldir/tree/2.0) branch? This has metadata support in a couple different ways. Field based, Header based, and disabled.

**Comment by Hubbitus** [comment]
Hello @jcustenborder.

Thanks for the good news. We are ready to try. Where I can find documentation about such options?

**Comment by jcustenborder** [comment]
@Hubbitus  yea ouch on that one. The docs are not published at the moment. You could run `mvn clean package` and it will compile the source of the v2 branch and in the `target/docs` folder is a bunch of generated documentation.
