### ISSUE TITLE
RFE: Spool remote dir

### ISSUE THREAD

**Issue by Avielyo10** [jcustenborder/kafka-connect-spooldir#118]
Let SpoolDir connector use input/output remote directories

**Comment by jcustenborder** [comment]
@Avielyo10 Can you elaborate on this one? Spooldir should be able to work against any posix filesystem. You could use a fuse filesystem to point it at s3 for example if needed.

**Comment by Avielyo10** [comment]
@jcustenborder I have an app with data that I want to spread out to several places.
I want to point to the app's directory with SpoolDir, is it possible?

**Comment by jcustenborder** [comment]
@Avielyo10 You're not giving me a ton of information to work on so sorry if I'm asking a lot of questions. Can you give me an example of what several places means? Does this mean several directories on a system or does this mean several different hosts? Are you talking about a filesystem with subdirectories? If you could give some examples that would be helpful.

**Comment by Avielyo10** [comment]
@jcustenborder 
I have an app that produces logs & XMLs (directory with subdirectories), I want to send them to kafka so kafka will push them into S3 && Polarion
