### ISSUE TITLE
How to import raw csv

### ISSUE THREAD

**Issue by dinegri** [jcustenborder/kafka-connect-spooldir#123]
Hi,

I am looking for a way to add raw csv to a topic, I tried some setup but I am not able to achieve it. In my test I found out that without use key.schema and value.schema it uses connect schema, but my value.convert.schema.enable is false

Is it possible to do that?

**Comment by jcustenborder** [comment]
@dinegri Kafka Connect has a few layers that it runs. `Source Connector` -> `Transformations` -> `Converters` -> `Kafka Producer`.

This connector will take the CSV and it generates records with a schema. It'll read the first row as the header, and emit records for the following rows. Take a CSV that looks like this:

```
firstname,lastname,id
John,Doe,1
```

The connector will generate a record with the following schema. 
```
firstname: String
lastname: String
id: String
```

So now the connector is generating records that have the data and the schema. This doesn't control how the data is written to kafka. That step is handled by the converter. Let's say that I'm using the json converter with schemas disabled. The row above would show up as:
```
{"firstname":"John","lastname":"Doe","id":"1"}
```

The power of this connector is that you can use your own schema and have the connector do conversion on the fly. For example if you wanted the following schema to end up in Kafka:

```
firstname: String
lastname: String
id: Long
```

You can set the connector to do this conversion and it will convert the `id` to long on the fly. Even though this connector focuses on the schema, you don't actually have to use it at the converter level. That's your decision. You can have it write json, avro, whatever and it's configured at runtime.

If you literally want `John,Doe,1` to show up as the value in Kafka you should look at [SpoolDirLineDelimitedSourceConnector](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-spooldir/sources/SpoolDirLineDelimitedSourceConnector.html).

**Comment by dinegri** [comment]
Hi @jcustenborder 

Firstly, thank you all for this amazing project 

I had compared performance with others kafka connectors options, spool-dir has a great performance (read file and write to a kafka topic).

I got your point, thank you for you help
