### ISSUE TITLE
Multiple task support (increasing tasks.max doesn't create additional tasks)

### ISSUE THREAD

**Issue by gregroberti** [jcustenborder/kafka-connect-spooldir#13]
Not sure if this is a bug or if this feature actually isn't implemented.. I see the configuration option `tasks.max=1` which I've tried increasing, however, I still only seem to get a single task up and running. I have also tried creating multiple instances of this connector with the same value for `input.path` but I always end up with a `NullPointerException`

{"name":"spooldir-connector-1","connector":{"state":"RUNNING","worker_id":"localhost:28082"},"tasks":[{"state":"FAILED","trace":"java.lang.NullPointerException\n\tat io.confluent.kafka.connect.source.io.processing.csv.CSVRecordProcessor.lineNumber(CSVRecordProcessor.java:160)\n\tat io.confluent.kafka.connect.source.io.PollingDirectoryMonitor.poll(PollingDirectoryMonitor.java:231)\n\tat io.confluent.kafka.connect.source.SpoolDirectoryTask.poll(SpoolDirectoryTask.java:47)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n","id":0,"worker_id":"localhost:28082"}]}

**Comment by jcustenborder** [comment]
This is by design. If you are running distributed I can't ensure that each task is pulling a single file.
