### ISSUE TITLE
kafka csv without schema does not work

### ISSUE THREAD

**Issue by samyujialiu** [jcustenborder/kafka-connect-spooldir#132]
Hi there, We are now working on the Kafka connect parts. We need to input csv files into Kafka. The one with schema works, but the one without schema failed. Can you pls help us with that ? Many thanks 
![image](https://user-images.githubusercontent.com/28554109/84215454-61691f00-ab1a-11ea-97ab-72484339a839.png)
![image](https://user-images.githubusercontent.com/28554109/84215516-99706200-ab1a-11ea-9e89-c30809f1ae8b.png)

**Comment by jcustenborder** [comment]
@samyujialiu `input.file.pattern` is a regex that needs to match the whole file name. Try something like [^.+\.csv$](http://www.regexplanet.com/cookbook/ahJzfnJlZ2V4cGxhbmV0LWhyZHNyEwsSBlJlY2lwZRiAgIDSt-KVCgw/index.html)

**Comment by samyujialiu** [comment]
@jcustenborder  I tried it, but it still does not work. I just want to create the schema automatically other than create it .. Thanks

**Comment by jcustenborder** [comment]
@samyujialiu The value that I gave you above will work. They key to keep in mind is that it will apply that schema for every csv that matches the regex. You need to make sure that at least one file that matches that regex is in the directory.
