### ISSUE TITLE
csv connector state FAILED

### ISSUE THREAD

**Issue by leobekhuis** [jcustenborder/kafka-connect-spooldir#134]
Hi I am getting this status FAILED on a connector which I was testing a few weeks ago. I did not change anything but some how the state is FAILED. How should I read this trace, I have tried to unload and load the connector with new config details but no succes.

"connector": {
    "state": "FAILED",
    "worker_id": "127.0.1.1:8083",
    "trace": "java.lang.IllegalStateException: Could not find any input file(s) to infer schema from.\n\tat com.google.common.base.Preconditions.checkState(Preconditions.java:508)\n\tat com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnector.start(AbstractSpoolDirSourceConnector.java:68)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:110)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:135)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)\n\tat org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:257)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1190)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:126)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1206)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1202)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"
  }

**Comment by jcustenborder** [comment]
@leobekhuis There were no files for it to infer a schema from when it started. Inferring the schema is really for the first run. It needs a file to try and parse the schema.

**Comment by jcustenborder** [comment]
@leobekhuis Your best bet is to go grab the schema it used previously to start and put that in your config.
