### ISSUE TITLE
How do you make the producer so fast?

### ISSUE THREAD

**Issue by xs005** [jcustenborder/kafka-connect-spooldir#137]
I have been using your library for quite a long time and I love it. I am trying to build one with Python because I have to add some additional fields based on the original data. My code is very slow. Kafka-connect-spooldir can ingest 100MB file within 1 min, but my code needs more than 10 min. I found that librdkafka gets them delivered to kafka in a very slow way, and I always got **Local: Queue full** error and I have to flush when the queue is full. 

I try to read your code but it is complex for me. Do you have any suggestion for python code to speed up a producer?

**Comment by jcustenborder** [comment]
@xs005 I tend to spend most of time time in Java but it's going to boil down to a few things. Librdkafka is crazy fast. It's most likely going to be settings. batch size is always important in kafka. make sure that you're not synchronously processing one message at a time. Spooldir sends hundreds or thousands of messages per poll. This drastically reduces the round trips to the brokers.

**Comment by xs005** [comment]
I guess the app is doing synchronously processing one message at a time. I am looking for an example how to do that asynchronous. And I was told in the kafka slack that Librdkafka is default asynchronous, and I am very confused about how to do that. Thank you for your reply.
