### ISSUE TITLE
Record columns count swapped with schemaConfig columns count

### ISSUE THREAD

**Issue by gregroberti** [jcustenborder/kafka-connect-spooldir#14]
I believe that the values for record columns count and schemaConfig columns count has been reversed!

      Preconditions.checkState(this.valueParserConfig.mappings.size() == record.length, "Record has %s columns but schemaConfig has %s columns.",
          this.valueParserConfig.mappings.size(),
          record.length
      );

Found this bug while checking to see if a schema that has additional columns can be used to parse a CSV file that is missing some of these additional columns.

**Comment by jcustenborder** [comment]
@gregroberti Can you help me out with a test case? That would be great! The original idea didn't think about missing columns. It could work ok given we an optional schema.

**Comment by jcustenborder** [comment]
This was fixed with #17.
