### ISSUE TITLE
Getting a Server Exception, it is not able to flush 

### ISSUE THREAD

**Issue by candalay** [jcustenborder/kafka-connect-spooldir#144]
Hi I am trying to connect Kafka Cluster and receiving this error. Same configurations for Kafka File Stream Source connector is worked. Could you please give idea about it?

Task is failed but it moved the file to finished folder, I could not see the data in my Consumer. I am using LineDelimeted Source connector of Spooldir with Kafka-Connect base image.

"confluentinc/cp-kafka-connect-base:latest" also tested with 5.1.3 version

[2020-08-28 21:26:15,524] ERROR WorkerSourceTask{id=spooldirfile-source-test2-0} failed to send record to test.topic: (org.apache.kafka.connect.runtime.WorkerSourceTask)

org.apache.kafka.common.errors.UnknownServerException: The server experienced an unexpected error when processing the request.

Failed to flush, timed out while waiting for producer to flush outstanding 1 messages (org.apache.kafka.connect.runtime.WorkerSourceTask)

This is the configurations:

{"connector.class":"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirLineDelimitedSourceConnector","input.file.pattern":".*\\.txt","finished.path":"/home/finished","tasks.max":"1","name":"spooldirfile-source-test2","topic":"topicname","error.path":"/home/error/","input.path":"","value.converter":"org.apache.kafka.connect.storage.StringConverter"}

**Comment by jcustenborder** [comment]
@candalay The first thing I would do is ensure that your cluster is up and running well. Make sure that all of the brokers are addressable by DNS. This is most likely a problem with an unstable cluster.

**Comment by candalay** [comment]
Thanks for the answer.

With same connect configurations, I created another worker with org.apache.kafka.connect.file.FileStreamSourceConnector and it sent the data. It has same connector parameters.

Are there any Broker and kafka version compatibility restrictions for SpoolDir?

**Comment by jcustenborder** [comment]
@candalay Not really. It should work with any version that supports headers. Make sure that all of your partitions are online. You also most likely are not going to want the value.converter to be the StringConverter. You might want to try the JsonConverter instead.

**Comment by candalay** [comment]
Still the same. What do you mean by headers? Might be I will check on Monday.

Also, I have some SSL configurations, not sure if it has any effect?

CONNECT_SECURITY_PROTOCOL=SSL
CONNECT_SSL_CLIENT_AUTH=none
CONNECT_SSL_KEYSTORE_LOCATION
CONNECT_SSL_KEYSTORE_PASSWORD
CONNECT_SSL_TRUSTSTORE_LOCATION
CONNECT_SSL_TRUSTSTORE_PASSWORD

**Comment by jcustenborder** [comment]
Kafka has support for storing headers on the each message. I think it was added to connect in 2.0. If you can give me much more of the log so we can dig in a little more.

**Comment by candalay** [comment]
[logs.txt](https://github.com/jcustenborder/kafka-connect-spooldir/files/5145714/logs.txt) uploaded logs

**Comment by candalay** [comment]
I got an error, when I tried to send record with Header. How can I disable or skip this for using SpoolDir

**Comment by candalay** [comment]
"metadata.location":"NONE" when I set this, it worked. It is about Kafka version. Thanks for the indication.
