### ISSUE TITLE
Are ARRAY / BYTES supported?

### ISSUE THREAD

**Issue by aaydgithub** [jcustenborder/kafka-connect-spooldir#147]
I have tried to use Schema.Type ARRAY and BYTES. But I couldn't make it work. Just wonder if ARRAY / BYTES are supported? Thanks.

**Comment by jcustenborder** [comment]
@aaydgithub If you just want the file as bytes can you take a look at this branch. It has a connector to read the entire contents of the file as the message.

https://github.com/jcustenborder/kafka-connect-spooldir/tree/issue-135

This adds a new connector that will read the entire file and it will be the value of the message to kafka. https://github.com/jcustenborder/kafka-connect-spooldir/blob/issue-135/src/main/java/com/github/jcustenborder/kafka/connect/spooldir/SpoolDirBinaryFileSourceConnector.java
