### ISSUE TITLE
Problem with logging

### ISSUE THREAD

**Issue by phucsnguyenv** [jcustenborder/kafka-connect-spooldir#148]
Hi team, 
I have some questions with Spooldir connector log. 

1. It generates so many log records for searching file, it's useful to check if the connector is running but it's too much, and hard to check other importance records. I think we can have option to turn it off or change the log level. 

2. Every time it proceed a file, the log seems not provide correct informaiton
```
INFO Finished processing 0 record(s) in 0 second(s). (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask)
```
Even the files that have many records still show `processing 0 record(s)`. This should show the actual proceeded records. 

3. I got a problem recently, sometimes my log records file is proceeded, but the data not pushed to Kafka. I can see my file is moved to finished folder, and the connect log shows that file is proceeded but data is not there. Do you know what happened? 

Thank you!

**Comment by jcustenborder** [comment]
Which connector are you using? The JSON, CSV, etc?

**Comment by sachin-rajwade** [comment]
I am also seeing the same problem we are the using the CSV spooldir

**Comment by jcustenborder** [comment]
Are you all using unique file names?

**Comment by sachin-rajwade** [comment]
yes

**Comment by sachin-rajwade** [comment]
No files matching input.file.pattern were found in /data/unprocessed/ncs/product_margin (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,765] INFO [NCS_FS_PRODUCT_MARGIN_SOURCE|task-1] No files matching input.file.pattern were found in /data/unprocessed/ncs/product_margin (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,765] INFO [NCS_FS_PRODUCT_MARGIN_SOURCE|task-0] No files matching input.file.pattern were found in /data/unprocessed/ncs/product_margin (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,766] INFO [NCS_FS_PRODUCT_MARGIN_SOURCE|task-3] No files matching input.file.pattern were found in /data/unprocessed/ncs/product_margin (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,766] INFO [NCS_FS_PRODUCT_MARGIN_SOURCE|task-2] No files matching input.file.pattern were found in /data/unprocessed/ncs/product_margin (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,856] INFO [ncs-fs-prod_returns-source|task-2] No files matching input.file.pattern were found in /data/unprocessed/ncs/prod_returns (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,856] INFO [ncs-fs-prod_returns-source|task-4] No files matching input.file.pattern were found in /data/unprocessed/ncs/prod_returns (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,862] INFO [ncs-fs-prod_returns-source|task-0] No files matching input.file.pattern were found in /data/unprocessed/ncs/prod_returns (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,898] INFO [ncs-fs-prod_returns-source|task-1] No files matching input.file.pattern were found in /data/unprocessed/ncs/prod_returns (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
kafka-connect               | [2021-12-01 05:51:53,898] INFO [ncs-fs-prod_returns-source|task-3] No files matching input.file.pattern were found in /data/unprocessed/ncs/prod_returns (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)

**Comment by jcustenborder** [comment]
What are you showing me here? This is normal operation. The task will return No Files matching input.file.pattern if the directory is empty. Do you have a way to reproduce this behavior? I'd be happy to look further given a little more info.

**Comment by sachin-rajwade** [comment]
> What are you showing me here? This is normal operation. The task will return No Files matching input.file.pattern if the directory is empty. Do you have a way to reproduce this behavior? I'd be happy to look further given a little more info.

Even thought its normal. I have six to seven file connectors and its hogs the kafka-connect logs and miss errors coming

**Comment by jcustenborder** [comment]
This is all handled by log4j under the hood. You can go change the log4j settings to accommodate to your liking. Changing the connector for this preference is not a possibility. You can increase the threshold for that logger to filter it out. 

Try adding this to your logging config. Most likely `connect-log4j.properties`

```
log4j.logger.com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue=WARN
```

**Comment by elayaraja-kv** [comment]
Thank you. Looks like we would like to implement the same in our docker environment. would be let us know correct env variable or JVMS argument?
