### ISSUE TITLE
Spooldir Line Delimited in Distributed mode?

### ISSUE THREAD

**Issue by candalay** [jcustenborder/kafka-connect-spooldir#150]
Hi,

Can Spooldir Line Delimited Source run in distributed mode?

Tahnks

**Comment by jcustenborder** [comment]
Any one of the connectors in this project can run in distributed mode assuming that you have shared storage that is mounted on all nodes in the connect cluster.

**Comment by candalay** [comment]
yes, it is checking the same storage but only one of them is checking the input folder, the other one is stopping after doing rebalancing. It has some cluster id and connect group id.

    curl -s -X PUT -H "Content-Type: application/json" --data '{"connector.class":"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirLineDelimitedSourceConnector",
    "tasks.max":"1","topic":"","input.file.pattern":".*\\.log","input.path":"/home/sender/input/",
"error.path":"/home/avr/sender/error","finished.path":"/home/sender/finished","value.converter":"org.apache.kafka.connect.storage.StringConverter",
    "key.converter":"org.apache.kafka.connect.storage.StringConverter","metadata.location":"NONE", "task.partitioner":"ByName", "batch.size": 10000, "file.buffer.size.bytes": 1048576}' http://localhost:8084/connectors/sender/config

**Comment by candalay** [comment]
can task.max value more than 1? when I set 3 nothing is changed

**Comment by jcustenborder** [comment]
Right now no. No matter what you put in the `tasks.max` it only creates a single task. I need to fix that. If you create more than one connector pointing to the same folder looking at the same files you are going to run into issues. Your input pattern is a regex so you might want to check that. I think you'd need `^.*.log$`. Even single threaded this connector is only doing a readline against each line of the file. Throughput should be pretty high unless you have a massive amount of small files. I'll put out a fix for supporting multiple tasks once I have a little more time available to test.

**Comment by candalay** [comment]
My expectation was 2 connector can check same folder and picks up 2 files at a time so with 2 pods application reads 2 files.

I am running two pods but receiving this error for second pod.

Discovered group coordinator address:9091 (id: 2147483646 rack: null)
Rebalance started
(Re-)joining group
Successfully joined group with generation 4
Joined group at generation 4 with protocol version 2 and got assignment: Assignment{error=0, leader='avr-sender-7cf4cc8698-j4qwd-0d35c128-d540-48b4-aac9-f4e2fce26ae9', leaderUrl='http://address:8084/', offset=4, connectorIds=[], taskIds=[], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0
Catching up to assignment's config offset.
Current config state offset -1 is behind group assignment 4, reading to end of config log
Finished reading to end of log and updated config snapshot, new config log offset: 4
Starting connectors and tasks using config offset 4
Finished starting connectors and tasks

**Comment by jcustenborder** [comment]
Did you correct the regex I pointed out earlier? When you say pod are you running on kubernetes? Distributed mode will not work without shared storage. The files to be processed must be on a NFS share that is mounted to all workers. If you are wanting to get something generated by another pod you could look into using this as a side car using standalone mode.

**Comment by candalay** [comment]
Yes it is kubernetes,  I am using your suggested regex "input.file.pattern":"^.*.log$"

No it is looking to same folder,  there is a mounted volume for both. When I deleted the other pod, second pod is starting to run.

**Comment by jcustenborder** [comment]
Don't try to use multiple connectors that are pointing to the same directory looking for the same files. The tasks use lock files to try to prevent this from happening. Can you give this branch a shot? It has a fix allowing multiple tasks from the same connector. 

https://github.com/jcustenborder/kafka-connect-spooldir/tree/issue-135

**Comment by candalay** [comment]
yes I tried with increasing tasks size : 2, it picked up with this branch https://github.com/jcustenborder/kafka-connect-spooldir/tree/issue-135. But if two files are in folder and if one of these are not marked with .PROCESSING. It is doing one by one. When this can be released? In any case it can be used for now, need to more test.

for previous case, I changed the connector name and both are working now. Thanks for your help.

And one more question: Somehow pod is failed and file is remain as .PROCESSING, after application is running again, will it continue from processing file or not? Similar case also if kafka cluster is down?

**Comment by jcustenborder** [comment]
The way files are selected by tasks isn't perfect because there is no way to synchronize between tasks that are on different machines. It basically uses  a `<hash of filename> % <total tasks> == task index` to figure out if the task should process it. Each task gets an index associated with it. It's not perfect but it gets you a pretty even distribution.
