### ISSUE TITLE
Question: how to limit reading 100 rows of CSV every 5 seconds?

### ISSUE THREAD

**Issue by JoeRakhimov** [jcustenborder/kafka-connect-spooldir#154]
I have CSV data. I want to simulate such a data stream: the consumer receives only 100 items every 5 seconds. I tried these properties:
```
batch.size = 100
empty.poll.wait.ms = 5000
```
However, data being processed fast. I think 'empty.poll.wait.ms' is used in another use case. My question is which property I need to set to simulate such behavior?

**Comment by jcustenborder** [comment]
The connect framework isn't really designed to do that. It's there to create a continuous flow of data. If I were going to attempt this I would implement a [Single Message Transform](https://kafka.apache.org/documentation/#connect_transforms). These get called for each record that is returned from this record. You would implement your rate limiting logic there. You could use something like the [Guava RateLimiter](https://guava.dev/releases/19.0/api/docs/index.html?com/google/common/util/concurrent/RateLimiter.html) to pull it off. I'm going to close this issue but feel free to ask any questions.
