### ISSUE TITLE
Scanning recursive directories 

### ISSUE THREAD

**Issue by ghost** [jcustenborder/kafka-connect-spooldir#159]
I have set up the spooldir connector on a unix machine and it seems to work well. I would like to know if there are a few things that can be done with spooldir

1. I want to create multiple directories inside the spooldir-scanning file path, create files of the provided format inside them and scan those too. How do i accomplish this?

2. I do not want the source files to move to different directories after completion/error. I tried providing the same path for source, target and error but the connector would not accept the value. 
Any way around these? would really appreciate the help.

thank you for making this amazing connector, its been very useful

**Comment by jcustenborder** [comment]
@Joe-Arul Item 2 can be done now. The main caviet you need to plan for is that if the connector restarts it will reimport all of the files. #1 could be added but isn't supported at the moment.

**Comment by bsdis** [comment]
hi, this is very much in line with what i need also.
How big a task would it be to add support for 1? (recursive handlng, including an ignore list of directories to be ignored, functionality  )
How big a task would it be to add support for 2 - such that if connection is lost, only not-sent-yet files will be imported (such that we do not re-send old files?

**Comment by bitsofinfo** [comment]
@jcustenborder @Joe-Arul how about something like this as a basic stab at it? https://github.com/bitsofinfo/kafka-connect-spooldir/commit/6533f78834a92258184ad8a90247e1ab278a64ae

**Comment by jcustenborder** [comment]
@bitsofinfo The main concern I've had with recursive support is how to handle the cleanup policies. We'd need to address it there as well.

**Comment by bitsofinfo** [comment]
so how about `files.walk.recursively=true` the entire structure from `input.path` -> `matched file` would be copied to `error/finished` just like things are today. Then if you have `files.walk.recursively.retain.walked.dirs=true (default false)` that intermediary structure would be left as is within `input.path`, the matched files would be moved, just the intermediary dirs would remain.

**Comment by jcustenborder** [comment]
You'd really need to copy the path structure. For example if my input directory looks like this:
```
/input/1/test.csv
/input/2/test.csv
```
this would get written to 
```
/finished/test.csv
```
That could be a problem.

**Comment by bitsofinfo** [comment]
yes thats what im saying in the latter comment.

**Comment by jcustenborder** [comment]
ok. on the same page now. Assuming we do this it would work.

**Comment by bitsofinfo** [comment]
assuming this `AbstractCleanUpPolicy` will come into play and `InputFile` might need an attr to indicate its "parentdirs" relative from `input.path`

**Comment by jcustenborder** [comment]
AbstractCleanupPolicy is created based on a [config](https://github.com/jcustenborder/kafka-connect-spooldir/blob/master/src/main/java/com/github/jcustenborder/kafka/connect/spooldir/AbstractCleanUpPolicy.java#L41) so we'd just need to refactor them to pass along the config.

**Comment by bitsofinfo** [comment]
yes, I think those behaviors still apply that are in there, its just that if the `files.walk.recursively` option is enabled AND `InputFile.<attrTBDthatIndicatesParentPath>` is present, it needs to take those dirs into account for the operations it does

**Comment by jcustenborder** [comment]
We'd need to determine the relative path of the input path and copy that across to the finished path.

**Comment by bitsofinfo** [comment]
yup, figured i could handle that in `InputFileDequeue.Deque` and just set it during construction of `InputFile` as a config addition or another arg.

**Comment by bitsofinfo** [comment]
@jcustenborder i added an implementation here: https://github.com/jcustenborder/kafka-connect-spooldir/pull/182 added some tests + some local testing seems to work fine. all tests passed, not sure why the merge conflict on those 2 files as my pull upstream had no conflicts.
