### ISSUE TITLE
log compact configuration support to retain data in topic 

### ISSUE THREAD

**Issue by dhirajsurve** [jcustenborder/kafka-connect-spooldir#160]
I am trying to create reference topic to retain value using log compact configuration  but with  Connector its not working as expected  .
--property  print.key=true --property key.separator=:

sample What I want to achieve
Create topic with log compactor setting
kafka-topics --create --zookeeper zookeeper:2181 --topic latest-product-price --replication-factor 1 --partitions 1 --config "cleanup.policy=compact" --config "delete.retention.ms=100"  --config "segment.ms=100" --config "min.cleanable.dirty.ratio=0.01"
Produce some recordskafka-console-producer --broker-list localhost:9092 --topic latest-product-price --property parse.key=true --property key.separator=:>p3:10$>p5:7$>p3:11$>p6:25$>p6:12$>p5:14$>p5:17$

Consume it
kafka-console-consumer --bootstrap-server localhost:9092 --topic latest-product-price --property  print.key=true --property key.separator=: --from-beginning
p3:11$
p6:12$
p5:14$
p5:17$
This is working fine , issue is  how to configure  --property parse.key=true  without changing the code .There is no way to set this property in for sftp connector

**Comment by jcustenborder** [comment]
@dhirajsurve Are you sure you have the correct connector? This connector does not natively support SFTP.

**Comment by dhirajsurve** [comment]
Here is the connector definition also not that ita customised for sftp 
Connector Defination  :
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: cgf-ref-apn-sftp-source
  namespace: cgf
  labels:
    strimzi.io/cluster: cgf-ref-apn-connect
spec:
  class: com.github.jcustenborder.kafka.connect.spooldir.SftpCsvSourceConnector
  tasksMax: 1
  config:
    deque.topic: "connect-deque-apn"
    bootstrap.servers: "odf-cluster-kafka-bootstrap:9093"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://odf-cluster-schema-registry:8081"
    monitor.poll.time.ms: "5000"
    sftp.host: "x.x.x.x”
    sftp.port: 22
    sftp.username: "$&&"
    sftp.password: "$$"
    input.file.pattern: "^REF_[a-zA-Z0-9_-]+\\.csv$"
    input.path: "/tmp/input/"
    error.path: "/tmp/error/"
    finished.path: "/tmp/finished/"
    duplicate.path: "/tmp/duplicate/"
    topic: "cgf-ref-apn-sftp-input"
    halt.on.error: "false"
    csv.first.row.as.header: "false"
    csv.null.field.indicator: "BOTH"
    key.schema: "{​​​​​​​​some key}
    value.schema: "{​​​​​​​​​​​​​​​​​​​​​Some value}

**Comment by jcustenborder** [comment]
I don't know how to help you. I have not written a SFTP connector. Where did you download com.github.jcustenborder.kafka.connect.spooldir.SftpCsvSourceConnector? This project has com.github.jcustenborder.kafka.connect.spooldir.CsvSourceConnector which is used for working against filesystems like NFS, CIFS, or a local file system.

**Comment by dhirajsurve** [comment]
I had customized to connect using sftp . Below thing works fine
In Addition to this if we create test topic with same configuration and add producer with --property parse.key=true then it works properly .

kafka-topics --create --zookeeper zookeeper:2181 --topic latest-product-price --replication-factor 1 --partitions 1 --config "cleanup.policy=compact" --config "delete.retention.ms=100" --config "segment.ms=100" --config "min.cleanable.dirty.ratio=0.01"

Produce some records
kafka-console-producer --broker-list localhost:9092 --topic latest-product-price --property parse.key=true --property key.separator=:
>p3:10$
>p5:7$
>p3:11$    <--- p3 is being overwritten 
>p6:25$
>p6:12$
>p5:14$
>p5:17$

Consume it

kafka-console-consumer --bootstrap-server localhost:9092 --topic latest-product-price --property parse.key=true --property key.separator=: --from-beginning
p3:11$   <-- latest value of p3 is being saved 
p6:12$
p5:17$

This is working fine , I think its producer property --property parse.key=true  need to set while producing data in connector
