### ISSUE TITLE
Unable to Build with Maven

### ISSUE THREAD

**Issue by lkaupp** [jcustenborder/kafka-connect-spooldir#178]
Try to follow your tutorial on:
https://www.confluent.de/blog/ksql-in-action-enriching-csv-events-with-data-from-rdbms-into-AWS/

checking out the repository (master and latest version 2.0.69) lead to the following error:
![image](https://user-images.githubusercontent.com/26430608/115571788-9f4cdd00-a2bf-11eb-973f-b39ec4e6d82f.png)

Furthermore downloaded the mentioned missing jar from:
`https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-avro-converter/versions/5.2.1/confluentinc-kafka-connect-avro-converter-5.2.1.zip`
and did a manuall install:
`mvn install:install-file -Dfile=kafka-connect-avro-converter-5.2.1.jar -DgroupId=io.confluent -DartifactId=kafka-connect-avro-converter -Dversion=5.2.1 -Dpackaging=jar`
Next, i got a null pointer exception:
![image](https://user-images.githubusercontent.com/26430608/115572710-711bcd00-a2c0-11eb-9f76-c251f26ccd1b.png)

Tried with OpenJDK13 and OpenJDK14 - first in windows, second in WSL2-Ubuntu 20.04.

Any advice?

**Comment by jcustenborder** [comment]
@lkaupp This is a new handy feature of [Maven 3.8.1+](https://maven.apache.org/docs/3.8.1/release-notes.html#how-to-fix-when-i-get-a-http-repository-blocked). There are already built versions out [there](https://www.confluent.io/hub/jcustenborder/kafka-connect-spooldir).  I'd start by just downloading it directly from Confluent. Please feel free to reopen if you have any questions.

Created an issue to correct this in the parent pom. We'll get it in a future release.
jcustenborder/kafka-connect-parent#33

**Comment by lkaupp** [comment]
Anyhow is the avro schema creator / generation accessible from outside of the compiled version? That is the most interesting feature that i want to use without configuring everything manually.

**Comment by jcustenborder** [comment]
haha I have to admit. It's a feature that I hate. The idea behind it is to get you something that you can edit to a better schema. You just need to add things to the kafka classpath and run it. So use something like this. Here is an example in the [documentation](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-spooldir/sources/SpoolDirCsvSourceConnector.html). 

```
export CLASSPATH="$(find target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir -type f -name '*.jar' | tr '\n' ':')"
kafka-run-class com.github.jcustenborder.kafka.connect.spooldir.AbstractSchemaGenerator -t csv -f src/test/resources/com/github/jcustenborder/kafka/connect/spooldir/csv/FieldsMatch.data -c config/CSVExample.properties -i id
```

In your case you'd just replace `target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir` with where you extracted the zip you download.

**Comment by lkaupp** [comment]
i understand. I build something similiar two years ago for a research project in order to convert logs to a valid parseable json-schema with its datatypes for the usage in apache flink. I know how basic it is and how much you have to tweak in the end, but if you work with industrial sized log files in research you do not want to create a schema by hand with 200+ columns on each csv you interfere 😃
