### ISSUE TITLE
plugin.properties invalid Schema - with SchemaGenerator

### ISSUE THREAD

**Issue by lkaupp** [jcustenborder/kafka-connect-spooldir#179]
Hi @jcustenborder me again. Got everything setup so far but now i got an invalid schema exception with this config (Config is C&P from your SchemaGenerator, only replaced string to AVRO configuration):
```
class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
name=test-opcua-1
tasks.max=1
halt.on.error=false
topic=logs2
key.schema={"name"\:"com.github.jcustenborder.kafka.connect.model.Key","type"\:"STRUCT","isOptional"\:false,"fieldSchemas"\:{"date"\:{"type"\:"int", "logicalType"\:"timestamp-millis","isOptional"\:true}}}
csv.first.row.as.header=true
finished.path=/data/finished/opcua
error.path=/data/error/opcua
input.path=/data/unprocessed/opcua
value.schema={"name"\:"com.github.jcustenborder.kafka.connect.model.Value","type"\:"STRUCT","isOptional"\:false,"fieldSchemas"\:{"date"\:{"type"\:"int", "logicalType"\:"timestamp-millis","isOptional"\:true},"nodeid"\:{"type"\:"STRING","isOptional"\:true},"value"\:{"type"\:"STRING","isOptional"\:true},"dtype"\:{"type"\:"STRING","isOptional"\:true}}}
```

with this exception:
'contains no connector type'

i try to start 'connect-standalone worker.properiest above.config.properites'.
Here is my worker.properties:
````
rest.port=8083
plugin.path=/usr/share/java,/usr/share/confluent-hub-components
bootstrap.servers=broker:9092

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
key.converter=io.confluent.connect.avro.AvroConverter
value.converter=io.confluent.connect.avro.AvroConverter

key.converter.schemas.enable=true
value.converter.schemas.enable=true

offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
````

**Comment by lkaupp** [comment]
found the issue. it is not class anymore its 'connector.class'... lovely inconsistency

**Comment by jcustenborder** [comment]
should that be `connector.class` instead of `class`

**Comment by jcustenborder** [comment]
oh hah. good timing. Was that the output directly from the generator? I don't see where the generator is setting `connector.class`

**Comment by lkaupp** [comment]
Nah it is a collection of different tutorials that i tried to combine and in the same time update to the latest version. I know u have plenty of things to do, and confluent for sure favor their cloud version, but its hard to setup everything in place on premise with the current version of documentation. You have to think a lot between the lines. Thankfully you are such a great person and answered all my questions :)
