### ISSUE TITLE
How to retrieve header infos in a Stream with KSQLDB?

### ISSUE THREAD

**Issue by fbvdka** [jcustenborder/kafka-connect-spooldir#193]
You mention that aach of the connectors in this plugin emit the following headers for each record written to kafka.

- file.path - The absolute path to the file ingested.
- file.name - The name part of the file ingested.
- file.name.without.extension - The file name without the extension part of the file.
- file.last.modified - The last modified date of the file.
- file.length - The size of the file in bytes.
- file.offset - The offset for this piece of data within the file.

What I would like is to know when we have the last message of a specific connector (CSV actually). I use KSQLDB but I do not see how to have these infos?

Thanks in advance,

**Comment by jcustenborder** [comment]
You would need to use a single message transform to copy the header to a field. I don’t believe ksql has header support.

**Comment by fbvdka** [comment]
Thank you!
Actually, there is no header support in KSQLDB. 
Hope it will available soon https://github.com/confluentinc/ksql/pull/8293
