### ISSUE TITLE
Multiple files with different schema in same directory

### ISSUE THREAD

**Issue by selvakumarEsra** [jcustenborder/kafka-connect-spooldir#20]
how to support a folder with different type of files with different schema? can it be achieved with configuration change?

**Comment by jcustenborder** [comment]
Do the files have a different naming scheme? Something like users001.csv? You could change the file name pattern to only accept this file name.

**Comment by jcustenborder** [comment]
I haven't heard back from you on this. Open it again if the suggestion I gave you does not work.
