### ISSUE TITLE
Continious logs coming in kafka connect logs 

### ISSUE THREAD

**Issue by sachin-rajwade** [jcustenborder/kafka-connect-spooldir#201]
No files matching input.file.pattern were found in /data/unprocessed/kdg/order_data

continious logs are coming when no files exist in the unprocessed folder. Please help

**Comment by jcustenborder** [comment]
@sachin-rajwade It would help if you posted what those log messages are. This connector is designed to run continuously. Meaning it will continue to check the directory of `input.path` after it has processed all of the files in the folder. If no files are found that match the input pattern, it will check again and again.

**Comment by sachin-rajwade** [comment]
> re coming when no files exist in th
"[2022-02-27 07:10:14,994] INFO [NCS_FS_PRODUCT_MARGIN_FILE_SOURCE_CONNECTOR|task-2] No files matching input.file.pattern were found in /data/unprocessed/ncs/product_margin (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)"

The above comes continuously and what happens is that we are missing errors from other connectors.

**Comment by jcustenborder** [comment]
@sachin-rajwade I would look at altering the logger level on `com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue` to `warn`. This will eliminate the log message.
