### ISSUE TITLE
kafka-connect-spooldir in public maven central repository

### ISSUE THREAD

**Issue by selvakumarEsra** [jcustenborder/kafka-connect-spooldir#21]
is there any plan put the kafka-connect-spooldir jar into public maven central repository?

**Comment by jcustenborder** [comment]
@selvakumarEsra I wasn't planning on it. What use case were you thinking of?

**Comment by selvakumarEsra** [comment]
to pull the kafka-connect-spooldir for corporate use, it is better to add in public maven repo.

**Comment by jcustenborder** [comment]
All of my connectors are now being published to maven as well.

```xml
<dependency>    
   <groupId>com.github.jcustenborder.kafka.connect</groupId>   
   <artifactId>kafka-connect-spooldir</artifactId>    
   <version>1.0.13</version>
</dependency>
```
