### ISSUE TITLE
SpoolDirSourceConnector.validate(...) method throws IllegalStateException On empty config

### ISSUE THREAD

**Issue by hsm** [jcustenborder/kafka-connect-spooldir#29]
This issue is related to issue #22 . We are considering using Landoop as a way to configure and manage Kafka connectors. The Landoop UI has a nifty feature where it uses the Connector `validate` method to iteratively tell you what is wrong with the current configuration so you can fix it on the fly and in the end hopefully have a working connector.  

However, Landoop UI does not expect the validate method to throw an `IllegalStateException`. In the underlying framework, errors are reported by throwing a  `ConfigException`

We have actually done a bit of work (see https://github.com/TeletronicsDotAe/kafka-connect-spooldir ) on improving the validation in order to get informative error messages on configuration time, including adding the ability to specify dependent properties (such as when property A is foo, property B must be present). While preparing the pull request I've noticed that you have moved the `ValidDirectoryWritable` class out of the project into a different project. Would you consider changing your validator to throw `ConfigException`s instead of `IllegalStateException`s?

**Comment by jcustenborder** [comment]
@hsm Potentially yes I would consider changing it to ConfigException. First I need to verify that ConfigException is the correct exception. Assuming it is sure.

**Comment by jcustenborder** [comment]
@hsm I'm cool with this. I opened an issue in jcustenborder/connect-utils#49
