### ISSUE TITLE
Does it support multiple files in the directory

### ISSUE THREAD

**Issue by praveengone** [jcustenborder/kafka-connect-spooldir#32]
I am raising it as an issue as i did not find comments section. 

Is it having capability to read multiple different files to different topics in kafka or is it going to be always one file in the directory. Also can i use shared path URI in the input.path property value

**Comment by jcustenborder** [comment]
@praveengone You would need to run multiple instances of the connector. Basically you use the `input.file.pattern` to setup a pattern that will match one file type and map it to a schema. You can add another connector with a different `input.file.pattern` pointing to the same directory. For example persons.csv and companies.csv. They'll have different schemas for example and you can run multiple connectors for this.
