### ISSUE TITLE
Error while generating CSV schema (Documentation and Code Bug)

### ISSUE THREAD

**Issue by chaitanyabjoshi** [jcustenborder/kafka-connect-spooldir#37]
Disclaimer: I am absolute dumb in maven and allied technologies and hence perfect test target for documentation :D
Now, the instructions for CSV generating schema example do not work out of the box.
Below are problems explained which I faced.
Command mvn clean package works perfectly. No problems here.
Command `export CLASSPATH="$(find target/kafka-connect-target/usr/share/java -type f -name '*.jar' | tr '\n' ':')"` fails as there the directory oath under target is wrong.
For me correct path was: target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir
Lastly the final command expects a lot of directories to be created in /tmp and hence throws exceptions every time it is run. Following Exceptions are thrown one after the other.
`Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value '/tmp/input' must be a directory...`
`Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value '/tmp/spooldir/finished' must be a directory...`
`Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value '/tmp/error' must be a directory...`

I created following directories in order to run the command successfully.
`mkdir /tmp/input`
`mkdir /tmp/spooldir/`
`mkdir /tmp/spooldir/finished/`
`mkdir /tmp/error`

I think the code assumes those directories to be present. It should be either rectified or dependency on those directories should be removed.

**Comment by jcustenborder** [comment]
Hi @chaitanyabjoshi 

This is by design. These directories are required for the connector to start.
