### ISSUE TITLE
Incorrect offset handling of reprocessed JSON files

### ISSUE THREAD

**Issue by martinplank** [jcustenborder/kafka-connect-spooldir#40]
When reprocessing JSON file (e.g. because of an error), the offset of last processed record is looked up in Kafka in order to skip already processed lines. But there's a bug in line skipping code: One more line should be skipped.

I believe that there should be `<=` comparison (offset numbering is zero-based).

https://github.com/jcustenborder/kafka-connect-spooldir/blob/f14906f3fd81a79e7eb64dd0bf0411f0de374d4b/src/main/java/com/github/jcustenborder/kafka/connect/spooldir/SpoolDirJsonSourceTask.java#L64

You can try it with this config:
```
{
  "name": "test",
  "config": {
    "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector",
    "tasks.max": "1",
    "topic": "test",
    "file": "/tmp/input/test.json",
    "schema.generation.enabled": "true",
    "schema.generation.key.name": "test-key",
    "schema.generation.value.name": "test-value",
    "finished.path": "/tmp/finished",
    "input.file.pattern": "test.json",
    "error.path": "/tmp/error",
    "input.path": "/tmp/input"
  }
}
```

Take any file, e.g. 
```
{"f1": "value1"}
{"f1": "value2"}
{"f1": "value3"}
```
and load it in the input directory. Then load it again with the same name. Check the Kafka topic, the last line will appear twice. 

This can cause problems when reprocessing repaired file that was previously routed to error directory.

CSV reprocessing works fine.

**Comment by jcustenborder** [comment]
thanks @martinplank!

**Comment by prasinos** [comment]
The issue is still present in all releases from 1.0.29 onwards. The fix above was reverted (seemingly by accident) in commit 68b2e59226f01229915eabbc6529a421a5335c6d
Changing 1 to 0 in https://github.com/jcustenborder/kafka-connect-spooldir/blob/32d2d69d4ac1e3840a6866604397243a2707a5e3/src/main/java/com/github/jcustenborder/kafka/connect/spooldir/SpoolDirJsonSourceTask.java#L67 fixes the issue.
