### ISSUE TITLE
Cannot parse date

### ISSUE THREAD

**Issue by geopet85** [jcustenborder/kafka-connect-spooldir#49]
I am using v1.0.24 of the library with Kafka connect 4.0.0.

I am trying to parse a csv with values: 

`1,2018-03-12,2018-03-12,1200,A,B,2018-04-30T22:00:51.000Z` 

and schema:

`{"name":"Test","type":"STRUCT","isOptional":false,"fieldSchemas":{"id":{"type":"INT64","isOptional":false},"created":{"name" : "org.apache.kafka.connect.data.Date","type" : "INT32","version" : 1,"isOptional" : true},"updated":{"name" : "org.apache.kafka.connect.data.Date","type" : "INT32","version" : 1,"isOptional" : true},"logins":{"type":"INT64","isOptional":true},"category":{"type":"STRING","isOptional":true},"subcategory":{"type":"STRING","isOptional":true},"last_login":{"name" : "org.apache.kafka.connect.data.Timestamp","type" : "INT64","version" : 1,"isOptional" : true}}}`

but i am getting the following error:

> org.apache.kafka.connect.errors.DataException: Exception thrown while parsing data for 'created'. linenumber=1
> 	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.process(SpoolDirCsvSourceTask.java:126)
> 	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTask.read(SpoolDirSourceTask.java:293)
> 	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTask.poll(SpoolDirSourceTask.java:156)
> 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:179)
> 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
> 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.kafka.connect.errors.DataException: Could not parse '2018-03-12' to 'Date'
> 	at com.github.jcustenborder.kafka.connect.utils.data.Parser.parseString(Parser.java:113)
> 	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.process(SpoolDirCsvSourceTask.java:118)

Any idea what could be the cause of the issue?
Thank you.

**Comment by jcustenborder** [comment]
@geopet85 Take a look at [parser.timestamp.date.formats](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-spooldir/sources/SpoolDirCsvSourceConnector.html#parser-timestamp-date-formats). This allows your to specify date formats for the parser to try. The one you are using is not in the default of `yyyy-MM-dd'T'HH:mm:ss", "yyyy-MM-dd' 'HH:mm:ss`

**Comment by Rkregfor** [comment]
I have the same question. I have dates in format dd.MM.yyyy in my csv and trying to parse them using schema:

```
{
  "name": "com.github.jcustenborder.kafka.connect.model.Value",
  "type": "STRUCT",
  "isOptional": false,
  "fieldSchemas": {
    "Buchungstag": {
      "name": "org.apache.kafka.connect.data.Date",
      "type": "INT32",
      "version": 1,
      "isOptional": true
    },
    "Wertstellung": {
      "name": "org.apache.kafka.connect.data.Timestamp",
      "type": "INT64",
      "version": 1,
      "isOptional": true
    },
    "Vorgang": {
      "type": "STRING",
      "isOptional": false
    },
    "Buchungstext": {
      "type": "STRING",
      "isOptional": false
    },
    "Umsatz": {
      "name": "org.apache.kafka.connect.data.Decimal",
      "type": "BYTES",
      "version": 1,
      "parameters": {
        "scale": "2"
      },
      "isOptional": true
    }
  }
}
```

as part of connector config 

```
connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
csv.first.row.as.header=true
finished.path=/csv/finished
tasks.max=1
parser.timestamp.date.formats=[dd.MM.yyyy, yyyy-MM-dd'T'HH:mm:ss, yyyy-MM-dd' 'HH:mm:ss]
key.schema={"name":"com.github.jcustenborder.kafka.connect.model.Key","type":"STRUCT","isOptional":false,"fieldSchemas":{}}
csv.separator.char=59
input.file.pattern=umsaetze_.*.csv
topic=test-csv
error.path=/csv/error
input.path=/csv/input
value.schema={"name":"com.github.jcustenborder.kafka.connect.model.Value","type":"STRUCT","isOptional":false,"fieldSchemas":{"Buchungstag":{"name":"org.apache.kafka.connect.data.Date","type":"INT32","version":1,"isOptional":true},"Wertstellung":{"name":"org.apache.kafka.connect.data.Date","type":"INT32","version":1,"isOptional":true},"Vorgang":{"type":"STRING","isOptional":false},"Buchungstext":{"type":"STRING","isOptional":false},"Umsatz":{"name":"org.apache.kafka.connect.data.Decimal","type":"BYTES","version":1,"parameters":{"scale":"2"},"isOptional":true}}}
```

Here is example of CSV

```
Buchungstag;Wertstellung;Vorgang;Buchungstext;Umsatz;
08.02.2019;08.02.2019;Lastschrift / Belastung;Auftraggeber: BlablaBuchungstext: Fahrschein XXXXXX Ref. U3436346/8423;-55,60;
08.02.2019;08.02.2019;Lastschrift / Belastung;Auftraggeber: Bank AGBuchungstext: 01.02.209:189,34 Ref. ZMKDVSDVS/5620;-189,34;
```

And I get following exception:
```
org.apache.kafka.connect.errors.ConnectException: org.apache.kafka.connect.errors.DataException: Exception thrown while parsing data for 'Buchungstag'. linenumber=2
    at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:277)
    at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.poll(AbstractSourceTask.java:144)
    ... 10 more
Caused by: org.apache.kafka.connect.errors.DataException: Could not parse '08.02.2019' to 'Date'
    at com.github.jcustenborder.kafka.connect.utils.data.Parser.parseString(Parser.java:113)
    ... 11 more
Caused by: java.lang.IllegalStateException: Could not parse '08.02.2019' to java.util.Date
    at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
    ... 12 more
```

Do you know what I am doing wrong, maybe scheme is incorrect? I am using parser.timestamp.date.formats=[dd.MM.yyyy, yyyy-MM-dd'T'HH:mm:ss, yyyy-MM-dd' 'HH:mm:ss] option

**Comment by mscaldas2012** [comment]
Hi there... Same issue here.

Hans anyone found a solution?

thanks,
