### ISSUE TITLE
partition assignment strategy

### ISSUE THREAD

**Issue by HanzhiWang1105** [jcustenborder/kafka-connect-spooldir#58]
Hi,
If I want send message to Partition on a round-robin method, how should I configure key.schema? 

For example, I have 600,000 messages to a topic with 6 partitions, I want each partition has balanced number of message, 100,000 per partitions. However, with the example data you provided, if I use "id" as key, all messages are sent to one partition and other 5 partitions have zero message.

Thank you a lot for your reply.

**Comment by jcustenborder** [comment]
@HanzhiWang1105 The easiest way would be to create a transform that sets the key to null. This will roundrobin all the data.
