### ISSUE TITLE
Namespace in Schema

### ISSUE THREAD

**Issue by sergeiwaigant** [jcustenborder/kafka-connect-spooldir#65]
Hi there,

we are using that connector for uploading several CSVs to Kafka as AVRO data.
When the connector initially consumes a file, it generates the Schema and create it in the Schema Registry.
The problem now is, that all schemas has the same namespace "com.github.jcustenborder.kafka.connect.model".

We consume the messages from multiple topics in one Java application and we have problems dealing with the same namespace here.

Is there a way to deal with that? Would be nice to have an option to set a given namespace for every connector.

Kind regards
-Sergei

**Comment by jcustenborder** [comment]
@sergeiwaigant The best thing for you to do is pass in your own schema. This allows you to use whatever name you want. Take a look at `key.schema` and `value.schema`.  This can be used to generate a starting point. https://github.com/jcustenborder/kafka-connect-spooldir#csv
