### ISSUE TITLE
kafka version not comptabile

### ISSUE THREAD

**Issue by vbharghavi** [jcustenborder/kafka-connect-spooldir#68]
Kafka version available in our environment is lower than the Kafka  used for the compilation of this source code. Can you please tell if i can still use this code by tweaking.

Error which i am getting as of now is  **Header cannot be resolved to be a type**

**Comment by jcustenborder** [comment]
You need to use a newer version of Kafka Connect. You should be able to run a 2.0.0 kafka connect against a 0.11.0.0 broker.
