### ISSUE TITLE
File processing fails in the middle

### ISSUE THREAD

**Issue by Ehmeed** [jcustenborder/kafka-connect-spooldir#72]
Sometimes when I copy new file into connectors directory, it will process only batch.size * N records, not the whole file (eg only 2000 records from 8347 records).
Also there is empty *.PROCESSING file created besides the original file.
I am running two spooldir connectors looking into same directory for different file pattern.

**Comment by jcustenborder** [comment]
It would be good to understand what exception you are seeing. The connector will fail part way through if it can't parse the data.

**Comment by Ehmeed** [comment]
I don't think it's an issue with parsing, because I don't see any exception logged and if I remove the file, remove the *.PROCESSING file, and copy the original file into connectors directory, it will load it without a problem.

**Comment by graham2071** [comment]
Same issue here. I have also a lot of different connectors.
My guess is that when adding the connectors, a rebalance is triggered. The SpooldirCsvSourceTask is stopped, but it does not remove the PROCESSING file. When the task restarts, the files are then skipped.

**Comment by jcustenborder** [comment]
@graham2071 That is an interesting idea. Connector rebalancing could cause something like this to happen. Maybe we could look at closing the existing file and removing the .processing file when the connector restarts.

**Comment by jcustenborder** [comment]
#93 seems to be related as well.
