### ISSUE TITLE
Using Array in value.schema

### ISSUE THREAD

**Issue by brary** [jcustenborder/kafka-connect-spooldir#75]
I want to send an Array in one of the fields of Value.schema. Is there any way to do that? It works if I write: value.schema={"name" : "display-vavbab","type" : "STRUCT","isOptional" : false,"fieldSchemas" : {"top10items" : {"type" : "STRING","isOptional" : false}}} , But I want the type of "top10items" to be an array.

**Comment by jcustenborder** [comment]
Hi @brary!

Sorry about the delay. I missed you opening this issue. What format is this? If the files are JSON then this is pretty easy to do. If the files are CSV there isn't an easy way to do this in the connector. It would be really easy to do this in a single message transformation. You could use this to parse the file most of the way there, then use a SMT to split the field by whatever delimiter you need.
