### ISSUE TITLE
Some float64 values in CSV files show up as scientific notation in Kafka topic 

### ISSUE THREAD

**Issue by eksantrik** [jcustenborder/kafka-connect-spooldir#76]
Hello folks,

My kafka-connect import from CSV to Kafka mostly works except this specific column called CCR. I defined it as "CCR":{"type":"FLOAT64","isOptional":true} in values section. This value mostly varies between 0 and 1. I noticed that the value shows up as X.0E-4 when it is 0.000X. For example, when 0.0004 gets imported to Kafka, it becomes 4.0E-4. How can I make sure the value in Kafka is 0.0004.

Thanks,

**Comment by jcustenborder** [comment]
Are you using the JsonConverter? Basically what we're doing under the hood is parsing the text to a float of `0.0004`. This is placed in a struct and then handed off to the converter. What is most likely happening is the converter is then writing this data like this.

**Comment by eksantrik** [comment]
Yes, I am using the JSON converter. Is there any fix for this?

**Comment by jcustenborder** [comment]
This is something that should be handled in AK.

**Comment by jcustenborder** [comment]
I added a jira for it [KAFKA-7900](https://issues.apache.org/jira/browse/KAFKA-7900)

**Comment by eksantrik** [comment]
Thank you
