### ISSUE TITLE
Adding spooldir as plugin to kafka-connect raises java.lang.NoClassDefFoundError Exception

### ISSUE THREAD

**Issue by anastath** [jcustenborder/kafka-connect-spooldir#81]
Hi all, 
Thank you for the connector, I'm in the process of evaluating/testing it. My goal is to use it as a plugin to Kafka connect so as to create a new connector of this type 
`connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector`
To set up my environment, I used kafka, zookeeper and kafka-connect docker images I pulled from docker hub. I also use docker compose.
I first cloned this repo locally and packaged it with maven, using your instructions.
`Building on you workstation
git clone git@github.com:jcustenborder/kafka-connect-spooldir.git
cd kafka-connect-spooldir
mvn clean package
`
Then, In my docker-compose.yml file, I added to the kafka-connect image a new environment variable as follows:
`CONNECT_PLUGIN_PATH: "/etc/kafka-connect/jars"`
and a volume pointing from /etc/kafka-connect/jars to the directory where I have saved the packaged jar.

The thing is, that after running docker compose 
`docker-compose -f docker-compose.yml up`
the kafka-connect container exited after logging the exception below in the logs   
`...Exception in thread "main" java.lang.NoClassDefFoundError: com/github/jcustenborder/kafka/connect/utils/VersionUtil ...`
The workaround I used was to manually download the missing source file from here 
[https://github.com/jcustenborder/connect-utils/blob/master/connect-utils/src/main/java/com/github/jcustenborder/kafka/connect/utils/VersionUtil.java](url), add it to the src path (/src/main/java/com/github/jcustenborder/kafka/utils) within the downloaded repo and then try again to produce the jar with maven
`mvn clean package`.
By using the new jar as the loaded plugin, all worked like a charm.

**Comment by jcustenborder** [comment]
You need to include all of the dependencies and not just the jar. Look at the zip output.

**Comment by Avielyo10** [comment]
@jcustenborder , I encountered the same problem, `connect-utils` isn't a part from the dependencies

**Comment by jcustenborder** [comment]
@Avielyo10 This is because you didn't copy over the dependencies. Look in `target/kafka-connect-target/` and you'll see several dependencies. You need make sure that you are running `mvn clean package` and pulling in all of the dependencies. You can also look at `target/components/packages/` and take the zip. That is what is deployed to the Confluent hub.

```
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/jackson-databind-2.9.8.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/jackson-core-2.9.8.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-logging-1.2.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/reflections-0.9.11.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/error_prone_annotations-2.2.0.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/extended-log-format-0.0.2.13.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/checker-qual-2.5.2.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/opencsv-4.5.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/connect-utils-0.4.156.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/jackson-annotations-2.9.0.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/failureaccess-1.0.1.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-collections4-4.2.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/guava-27.1-jre.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/value-2.5.5.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/javassist-3.21.0-GA.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/kafka-connect-spooldir-1.0-SNAPSHOT.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/j2objc-annotations-1.1.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-collections-3.2.2.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-compress-1.18.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/freemarker-2.3.28.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/animal-sniffer-annotations-1.17.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/jsr305-3.0.2.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-text-1.3.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-beanutils-1.9.3.jar
target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/commons-lang3-3.8.1.jar
```

**Comment by Avielyo10** [comment]
@jcustenborder Works now!thanks!
