### ISSUE TITLE
Include source file name for line delimited connector

### ISSUE THREAD

**Issue by KristofferHumle** [jcustenborder/kafka-connect-spooldir#94]
When importing raw data in a line-by-line fashion it is very likely that validation and further processing will reveal errors in the underlying data.  

Given a false record it would be very helpful with a link to the origin input file. With this information it would be possible to trace back errors to the actual source and fix root cause.

Considering the line delimited connector one possible solution could be to add a config that would enable using the filename as key for the record produced. This would also make it possible to process records in per-file-order as records from the same file would end up on the same partition. On the downside this will impose some restrictions on the degrees on parallel processing on a single file.

**Comment by jcustenborder** [comment]
If we included this as a header would that work for you? I would prefer not to alter the payload of the body.

**Comment by KristofferHumle** [comment]
Currently it is not possible to access the RecordContext from the Streams DSL. Hence to use the filename one would have to use the Processor API. Having said that is seems like DSL support will be added at some point (https://cwiki.apache.org/confluence/display/KAFKA/KIP-159%3A+Introducing+Rich+functions+to+Streams).

I agree that adding the file meta data as headers is the best solution and we could modify down stream to use the processor api until DSL support is made available.

**Comment by jcustenborder** [comment]
@KristofferHumle Sorry about the delay. What if we add it in a header and for your use case you can use a SMT to move the header to a field?

**Comment by KristofferHumle** [comment]
That's perfect :-) I ended up using the processor api reading the header from the context anyway.

**Comment by DevalNaik** [comment]
Is this functionality available now?

**Comment by jcustenborder** [comment]
@DevalNaik Yes it hasn't been merged to master but it's part of the [2.0 release](https://github.com/jcustenborder/kafka-connect-spooldir/tree/2.0) which will be out soon.
